export const ERROR_MESSAGES = {
  USER_NOT_FOUND: "Usuario no encontrado",
  FAILED_TO_CREATE_USER: "Error al crear usuario",
  FAILED_TO_CREATE_SESSION: "Error al crear sesión",
  FAILED_TO_UPDATE_USER: "Error al actualizar usuario",
  FAILED_TO_GET_SESSION: "Error al obtener sesión",
  INVALID_PASSWORD: "Contraseña incorrecta",
  INVALID_EMAIL: "Email incorrecto",
  INVALID_EMAIL_OR_PASSWORD: "Email o contraseña incorrectos",
  SOCIAL_ACCOUNT_ALREADY_LINKED: "Cuenta social ya vinculada",
  PROVIDER_NOT_FOUND: "Proveedor no encontrado",
  INVALID_TOKEN: "Token incorrecto",
  ID_TOKEN_NOT_SUPPORTED: "Token de ID no soportado",
  FAILED_TO_GET_USER_INFO: "Error al obtener información de usuario",
  USER_EMAIL_NOT_FOUND: "Email no encontrado",
  EMAIL_NOT_VERIFIED: "Email no verificado",
  PASSWORD_TOO_SHORT: "Contraseña demasiado corta",
  PASSWORD_TOO_LONG: "Contraseña demasiado larga",
  USER_ALREADY_EXISTS: "Usuario ya existe",
  EMAIL_CAN_NOT_BE_UPDATED: "Email no puede ser actualizado",
  CREDENTIAL_ACCOUNT_NOT_FOUND: "Cuenta de credencial no encontrada",
  SESSION_EXPIRED: "Sesión expirada",
  FAILED_TO_UNLINK_LAST_ACCOUNT: "Error al desvincular última cuenta",
  ACCOUNT_NOT_FOUND: "Cuenta no encontrada",
  USER_ALREADY_HAS_PASSWORD: "Usuario ya tiene contraseña",
  FORBIDDEN: "Tu cuenta está inactiva. Por favor contacta al administrador.",
  UNAUTHORIZED:
    "Tu cuenta está inactiva o ya no existe. Por favor contacta al administrador.",
  "": "Error al actualizar contraseña",
};
